version: "3"

services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cardapio-app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
